pornfilterweb/registrasi/urls.py
# Talk urls
from django.conf.urls import patterns, url
from registrasi import views
from django.contrib import admin
from django.conf import settings
urlpatterns = patterns(
    'registrasi.views',
    url(r'^registrasi/$', 'registrasi'),
    url(r'^registrasi/save_registration/$', 'save_registration'),
    url(r'^user/$', views.user_list, name='user_list'),
    url(r'^user/search/$', views.user_search, name='user_search'),
    url(r'^user/add/$', views.user_edit, name='user_add'),
    url(r'^user/mod/(?P<user_id>\d+)/$', views.user_edit, name='user_mod'),
    url(r'^user/del/(?P<user_id>\d+)/$', views.user_del, name='user_del'),

)

pornfilterweb/talk/urls.py
# Talk urls
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'talk.views',
    url(r'^$', 'home'),
    url(r'^browsing/$', 'browsing'),
    url(r'^text_process/$', 'text_process'),
    url(r'^image_process/$', 'image_process'),
    url(r'^text_image_process/$', 'text_image_process'),
    url(r'^video_process/$', 'video_process'),
)

pornfilterweb/talk_project/urls.py
from django.conf.urls import patterns, include, url
from talk_project.views import logout_page
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', 'django.contrib.auth.views.login'),
    (r'^logout/$', logout_page),
    url(r'^', include('talk.urls')),
    url(r'^', include('registrasi.urls')),
    url(r'^registrasi/', include('registrasi.urls', namespace='registrasi')),

)

pornfilterweb/registrasi/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Registrasi(models.Model):
    mode = models.TextField()
    ip = models.TextField()

    def __unicode__(self):
        return self.ip+' - '+self.mode

pornfilterweb/registrasi/forms.py
from django import forms
from registrasi.models import Registrasi


class RegistrasiForm(forms.ModelForm):
    class Meta:
        model = Registrasi
        # exclude = ['author', 'updated', 'created', ]
        fields = ['mode','ip']
        widgets = {
            'mode': forms.TextInput(
                attrs={'id': 'mode','value':''}
            ),
            'ip': forms.TextInput(
                attrs={'id': 'ip','value':''}
            ),
        }

pornfilterweb/registrasi/views.py
from django.shortcuts import render
from django.http import HttpResponse
from registrasi.models import Registrasi
from registrasi.forms import RegistrasiForm
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.template import RequestContext
import subprocess
import json
#from ipware.ip import get_real_ip
def registrasi(req):
    tmpl_vars = {
        'form': RegistrasiForm()
    }
    return render(req, 'registrasi/index.html',tmpl_vars)

def save_registration(request):
    if request.method == 'POST':
        mode = request.POST.get('mode')
        print mode
        ip = request.META.get("HTTP_X_FORWARDED_FOR", None)
        if ip:
            ip = ip.split(", ")[0]
        else:
            ip = request.META.get("REMOTE_ADDR", "")
        print ip
        #ip = '127.0.0.1'
        registrasicount = Registrasi.objects.filter(ip = ip).count()
        if (registrasicount==0):
            registrasi = Registrasi(mode=mode, ip=ip)
            registrasi.save()
        elif (registrasicount>0):
            Registrasi.objects.get(ip=ip).delete()
            registrasi = Registrasi(mode=mode, ip=ip)
            registrasi.save()
        response_data = {}
        response_data['result'] = 'IP ' + registrasi.ip + ' Registration mode ' + registrasi.mode + ' successful'
        print response_data['result']
        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )
def user_list(request):
    users = Registrasi.objects.all().order_by('id')
    return render_to_response('registrasi/user_list.html',
                              {'users': users},
                              context_instance=RequestContext(request))
def user_search(request):
    user_field = request.POST.get('user_field','default')
    if user_field:
        users = Registrasi.objects.filter(ip__contains=user_field)
    else:
        users = Registrasi.objects.all().order_by('id')
    return render_to_response('registrasi/user_search.html',
                              {'users': users},
                              context_instance=RequestContext(request))

def user_edit(request, user_id=None):
    if user_id:
        user = get_object_or_404(Registrasi, pk=user_id)
    else:
        user = Registrasi()
    
    if request.method == 'POST':
        form = RegistrasiForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            return redirect('registrasi:user_list')
    else:
        form = RegistrasiForm(instance=user)
        
    return render_to_response('registrasi/user_edit.html',
                              dict(form=form, user_id=user_id),
                              context_instance=RequestContext(request))

def user_del(request, user_id):
    user = get_object_or_404(Registrasi, pk=user_id)
    user.delete()
    return redirect('cms:user_list')

pornfilterweb/templates/registrasi/base.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <title>Content Filtering</title>
    <script src="http://202.169.224.53/static/scripts/jquery.min.js"></script>
    <!-- Foundation & FontAwesome -->
    <link rel="stylesheet" type="text/css" href="http://202.169.224.53/static/scripts/foundation.css">
    <script src="http://202.169.224.53/static/scripts/d3.v3.min.js"></script>
    <script type="text/javascript" src="http://202.169.224.53/static/scripts/trianglify.min.js"></script>

    <script type="text/javascript">
    // random background pattern
    $(function(){

      // See more options here: https://github.com/qrohlf/trianglify#options
      var ops = {
        noiseIntensity: 0,
      }
      var t = new Trianglify(ops);
      var pattern = t.generate(document.body.clientWidth, document.body.clientHeight);
      document.body.setAttribute('style', 'background-image: '+pattern.dataUrl);
    });
    </script>
      <style type="text/css">
      .comment{
        background:rgba(255,255,255,1);
        padding: 8px;
        margin-bottom:5px;
        border:none;
      }
      .white{
        background:rgba(255,255,255,1);
        padding-top: 10px;
        border:none;
      }
      .commentcenter{
        position:relative;
        left:43%;
      }
      input.textarea:focus{
        height:1.5em;
        resize:none;
      }
      textarea{
        height:1.5em;
        resize:none;
      }
    </style>

    {% block head %}
    {% endblock %}

  </head>

  <body>
  {% block content %}
  {% endblock %}
  </body>
</html>

pornfilterweb/templates/registrasi/base_cms.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}User Registered{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="http://202.169.224.53/css/bootstrap.css" rel="stylesheet">
<link href="http://202.169.224.53/css/bootstrap-theme.css" rel="stylesheet">
<link href="http://202.169.224.53/css/jquery-ui.css" rel="stylesheet">
<script src="http://202.169.224.53/js/jquery-1.11.1.min.js"></script>
<script src="http://202.169.224.53/js/bootstrap.js"></script>
<script src="http://202.169.224.53/js/jquery-ui.js"></script>
{% block extrahead %}{% endblock %}
</head>
<body>

    {% block content %}
      {{ content }}
    {% endblock %}

</body>
</html>

pornfilterweb/templates/registrasi/index.html
{% extends "registrasi/base.html" %}
{% block content %}
<br><br>
<script src="http://202.169.224.53/static/scripts/registrasi.js"></script>

<div class="row white">
    <div class="large-12 columns">
        <h2>User Registration</h2><br><br>
    </div>
</div>

<div class="row white">
    <div class="columns large-12">
        <form method="POST" id="registrasi-post">
            {% csrf_token %}
                <input type="hidden" name="mode" id="mode">
            <center>
            <table style="margin-top:-50px;border:none">
            <tr>
            <td>
                <input type="checkbox" class="text" style="-moz-appearance:none;width:30px;height:30px;" name="text" id="text">
            </td>
            <td>
                <label style="margin-left:-10px;margin-bottom:15px;font-size:20px">Text</label>
            </td>
            <td>
                <input type="checkbox" style="-moz-appearance:none;width:30px;height:30px;" name="image" id="image">
            </td>
            <td>
                <label style="margin-left:-10px;margin-bottom:15px;font-size:20px">Image</label>
            </td>
            <td>
                <input type="checkbox" style="-moz-appearance:none;width:30px;height:30px;" name="video" id="video">
            </td>
            <td>
                <label style="margin-left:-10px;margin-bottom:15px;font-size:20px">Video</label>
            </td>
            <td>
                <input type="submit" style="font-size: 20px;margin-bottom:15px;" value="Register" class="tiny button">
            <!--<button style="margin-top:5px;font-size: 20px;" value="Execute" type="button" id="execute" class="tiny button">Execute</button>-->
            </td>
            </tr>
            </table>
            </center>
            </form>
    </div>
</div>
<!-- The feed -->
<div class="row white">
    <div class="columns large-12">
        <div style="margin-left:20px" id="registrasi">
            <!--{% for post in all_posts %}
                <li>
                    <strong>{{ post.text }}</strong> -
                    <em>{{ post.author }}</em> -
                    <span>{{ post.created }}</span> -
                    <a id='delete-post-{{post.id}}'>delete me</a>
                </li>
            {% endfor %}
        -->
        </div>
    </div>
</div>
{% endblock %}

pornfilterweb/templates/registrasi/user_edit.html
{% extends "registrasi/base_cms.html" %}
{% load bootstrap %}

{% block title %}User Registered List{% endblock title %}

{% block content %}
<div style="margin-left:110px;margin-right:110px">
        <table style="margin-top:20px;border:none">
        <tr>
        <td>
        <a href="/" class="btn btn-primary">Content Filtering</a>
        <td>&nbsp</td>
        <td>
        <a href="/logout" class="btn btn-success">Logout</a>
        </td>
        </tr>
        </table>
    <h3 class="page-header">User Add/Edit</h3>
    {% if user_id %}
    <form action="{% url 'registrasi:user_mod' user_id=user_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'registrasi:user_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Save</button>
          <a href="{% url 'registrasi:user_list' %}" class="btn btn-danger">Back</a>
        </div>
      </div>
    </form>

</div>
{% endblock content %}

pornfilterweb/templates/registrasi/user_list.html
{% extends "registrasi/base_cms.html" %}
{% block title %}User Registered List{% endblock title %}
{% load staticfiles %}
{% block extrahead %}

{% endblock %}

{% block content %}
<div style="margin-left:110px;margin-right:110px">
        <table style="margin-top:20px;border:none">
        <tr>
        <td>
        <a href="/" class="btn btn-primary">Content Filtering</a>
        <td>&nbsp</td>
        <td>
        <a href="/logout" class="btn btn-success">Logout</a>
        </td>
        </tr>
        </table>
    <h3 class="page-header" >User Registered List</h3>
               <div id="custom-search-input">
                            <div class="input-group col-md-3">
                            <form action="{% url 'registrasi:user_search'%}" method="post">
                            {% csrf_token %}
                            <table>
                            <tr>
                            <td>
                                <input name="user_field" id="user_field" type="text" class="search-query form-control" placeholder="Search User" />
                            </td>
                            <td>
                                    <button type="submit" class="btn btn-danger">
                                    Search
                                    </button>
                            </td>
                            </table>
                            </form>
                            </div>
                        </div><br/>
    <a href="{% url 'registrasi:user_add' %}" class="btn btn-default">Add New User</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>IP User</th>
          <th>Mode</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <td>{{ user.id }}</td>
          <td>{{ user.ip }}</td>
          <td>{{ user.mode }}</td>
          <td>
            <a href="{% url 'registrasi:user_mod' user_id=user.id %}" class="btn btn-default btn-sm">Edit</a>
            <a href="{% url 'registrasi:user_del' user_id=user.id %}" class="btn btn-default btn-sm">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>
{% endblock content %}

pornfilterweb/templates/registrasi/user_search.html
{% extends "registrasi/base_cms.html" %}
{% block title %}User Registered List{% endblock title %}
{% load staticfiles %}
{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
<div style="margin-left:110px;margin-right:110px">
        <table style="margin-top:20px;border:none">
        <tr>
        <td>
        <a href="/" class="btn btn-primary">Content Filtering</a>
        <td>&nbsp</td>
        <td>
        <a href="/logout" class="btn btn-success">Logout</a>
        </td>
        </tr>
        </table>
    <h3 class="page-header" >User Registered List</h3>
                                    <a href="{% url 'registrasi:user_list' %}" class="btn btn-success">
                                        <span class="glyphicon glyphicon-arrow-left"></span>
                                    </a>
    <a href="{% url 'registrasi:user_add' %}" class="btn btn-default">Add New User</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>IP User</th>
          <th>Mode</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <td>{{ user.id }}</td>
          <td>{{ user.ip }}</td>
          <td>{{ user.mode }}</td>
          <td>
            <a href="{% url 'registrasi:user_mod' user_id=user.id %}" class="btn btn-default btn-sm">Edit</a>
            <a href="{% url 'registrasi:user_del' user_id=user.id %}" class="btn btn-default btn-sm">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>
{% endblock content %}